/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iislamsoft
 */
public class AccountingTable extends javax.swing.JFrame {

    /**
     * Creates new form AccountingTable
     */
    public AccountingTable() {
        initComponents();
        refreshTable();
        maleRbtn.setActionCommand("Male");
        femaleRbtn.setActionCommand("Female");
    }
    
    public void refreshTable() {

        DefaultTableModel defaultTableModel = (DefaultTableModel) accountingTable.getModel();
        defaultTableModel.setRowCount(0);
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "select * from Accounting_Employee_Table";
            ResultSet rs = statement.executeQuery(Query);
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("ID"));
                String fn = String.valueOf(rs.getString("FirstName"));
                String ln = String.valueOf(rs.getString("LastName"));
                String gender = String.valueOf(rs.getString("Gender"));
                String birthDate = String.valueOf(rs.getString("DateOfBirth"));
                String email = String.valueOf(rs.getString("Email"));
                String phone = String.valueOf(rs.getInt("PhoneNumber"));
                String address = String.valueOf(rs.getString("Address"));
                String hireDate = String.valueOf(rs.getString("HireDate"));
                String sal = String.valueOf(rs.getInt("Salary"));

                String tableData[] = {id, fn, ln, gender, birthDate, email, phone, address, hireDate, sal};
                defaultTableModel = (DefaultTableModel) accountingTable.getModel();
                defaultTableModel.addRow(tableData);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountingTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        birthDareCal = new de.wannawork.jcalendar.JCalendarComboBox();
        emailTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        hireDateCal = new de.wannawork.jcalendar.JCalendarComboBox();
        salTxt = new javax.swing.JTextField();
        maleRbtn = new javax.swing.JRadioButton();
        femaleRbtn = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        accountingTable.setBackground(new java.awt.Color(204, 51, 0));
        accountingTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        accountingTable.setForeground(new java.awt.Color(255, 255, 255));
        accountingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Gender", "Date of Birth", "Email", "Phone Number", "Address", "Hire Date", "Salary"
            }
        ));
        accountingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(accountingTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("ID :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Gender :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Date of Birth :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Phone Number :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Email :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Address :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Hire Date :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Salary :");

        idTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        firstNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lastNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        birthDareCal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        emailTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        phoneTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        addressTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        hireDateCal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        salTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        maleRbtn.setBackground(new java.awt.Color(255, 204, 153));
        genderGroup.add(maleRbtn);
        maleRbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        maleRbtn.setText("Male");

        femaleRbtn.setBackground(new java.awt.Color(255, 204, 153));
        genderGroup.add(femaleRbtn);
        femaleRbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        femaleRbtn.setText("Female");

        addBtn.setBackground(new java.awt.Color(0, 102, 102));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Insert");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(102, 102, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(102, 0, 51));
        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(204, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBtn.setText("Delete");

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back To Home Page");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addComponent(idTxt)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(maleRbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(femaleRbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lastNameTxt)
                            .addComponent(firstNameTxt)
                            .addComponent(birthDareCal, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(emailTxt)
                            .addComponent(phoneTxt)
                            .addComponent(addressTxt)
                            .addComponent(hireDateCal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maleRbtn)
                            .addComponent(femaleRbtn))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(birthDareCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(hireDateCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(salTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void accountingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountingTableMouseClicked
        DefaultTableModel defaultTableModel = (DefaultTableModel) accountingTable.getModel();
        int rowIndex = accountingTable.getSelectedRow();

        idTxt.setText(defaultTableModel.getValueAt(rowIndex, 0).toString());
        firstNameTxt.setText(defaultTableModel.getValueAt(rowIndex, 1).toString());
        lastNameTxt.setText(defaultTableModel.getValueAt(rowIndex, 2).toString());
        if (defaultTableModel.getValueAt(rowIndex, 3).toString().equals("Female")) {
            femaleRbtn.setSelected(true);
        } else {
            maleRbtn.setSelected(true);
        }
        emailTxt.setText(defaultTableModel.getValueAt(rowIndex, 5).toString());
        phoneTxt.setText(defaultTableModel.getValueAt(rowIndex, 6).toString());
        addressTxt.setText(defaultTableModel.getValueAt(rowIndex, 7).toString());
        salTxt.setText(defaultTableModel.getValueAt(rowIndex, 9).toString());

        SimpleDateFormat parser = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formatter = new SimpleDateFormat("MMM DD, YY");
        Date birthDate, hireDate;
        try {
            birthDate = parser.parse(defaultTableModel.getValueAt(rowIndex, 4).toString());
            hireDate = parser.parse(defaultTableModel.getValueAt(rowIndex, 8).toString());

            birthDareCal.setDate(birthDate);
            hireDateCal.setDate(hireDate);
        } catch (ParseException ex) {
            Logger.getLogger(HrTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accountingTableMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        maleRbtn.setActionCommand("Male");
        femaleRbtn.setActionCommand("Female");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String hireDateFormat = dateFormat.format(hireDateCal.getDate());
        String birthDateFormat = dateFormat.format(birthDareCal.getDate());

        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "insert into Accounting_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary, Department) Values ('"
                    + Integer.parseInt(idTxt.getText()) + "' , '" + firstNameTxt.getText() + "' , '" + lastNameTxt.getText() + "' , '" + genderGroup.getSelection().getActionCommand() + "' , '" + birthDateFormat
                    + "' , '" + emailTxt.getText() + "' , '" + Integer.parseInt(phoneTxt.getText()) + "' , '" + addressTxt.getText() + "' , '" + hireDateFormat + "' , '" + Float.parseFloat(salTxt.getText()) + "' , '" + "HR')";
            statement.executeQuery(Query);
            JOptionPane.showMessageDialog(this, "Data Added");

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

            refreshTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String hireDateFormat = dateFormat.format(hireDateCal.getDate());
        String birthDateFormat = dateFormat.format(birthDareCal.getDate());
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "update Accounting_Employee_Table set ID = '" + Integer.parseInt(idTxt.getText()) + "', FirstName = '" + firstNameTxt.getText()
                    + "' , LastName = '" + lastNameTxt.getText() + "', Gender = '" + genderGroup.getSelection().getActionCommand() + "', Email = '" + emailTxt.getText()
                    + "', PhoneNumber = '" + phoneTxt.getText() + "', Address = '" + addressTxt.getText() + "', Salary = '" + salTxt.getText() + "',HireDate = '" + hireDateFormat + "', DateOfBirth ='" + birthDateFormat + "' where ID = '" + Integer.parseInt(idTxt.getText()) + "'";

            statement.executeQuery(Query);
            JOptionPane.showMessageDialog(this, "Data Updated");

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

            refreshTable();
        } catch (SQLException ex) {
        }  
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) accountingTable.getModel();
        defaultTableModel.setRowCount(0);
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "select * from Accounting_Employee_Table where ID = '" + Integer.parseInt(idTxt.getText()) + "'";
            ResultSet rs = statement.executeQuery(Query);
            
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("ID"));
                String fn = String.valueOf(rs.getString("FirstName"));
                String ln = String.valueOf(rs.getString("LastName"));
                String genderType = String.valueOf(rs.getString("Gender"));
                String birthDate = String.valueOf(rs.getString("DateOfBirth"));
                String email = String.valueOf(rs.getString("Email"));
                String phone = String.valueOf(rs.getInt("PhoneNumber"));
                String address = String.valueOf(rs.getString("Address"));
                String hireDate = String.valueOf(rs.getString("HireDate"));
                String sal = String.valueOf(rs.getInt("Salary"));

                String tableData[] = {id, fn, ln, genderType, birthDate, email, phone, address, hireDate, sal};
                defaultTableModel = (DefaultTableModel) accountingTable.getModel();
                defaultTableModel.addRow(tableData);
                
                return;
            }

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Employee with entered data not exsit");
                refreshTable();
            }
            

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountingTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountingTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addressTxt;
    private de.wannawork.jcalendar.JCalendarComboBox birthDareCal;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleRbtn;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.ButtonGroup genderGroup;
    private de.wannawork.jcalendar.JCalendarComboBox hireDateCal;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JRadioButton maleRbtn;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField salTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
