/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author iislamsoft
 */
public class HomePage extends javax.swing.JFrame {

  
    public HomePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        maleRBtn = new javax.swing.JRadioButton();
        femaleRBtn = new javax.swing.JRadioButton();
        dateOfBirth = new de.wannawork.jcalendar.JCalendarComboBox();
        phoneTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        hireDate = new de.wannawork.jcalendar.JCalendarComboBox();
        emailTxt = new javax.swing.JTextField();
        deptList = new javax.swing.JComboBox();
        addEmployeeBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        hrTableBtn = new javax.swing.JButton();
        qManagementTableBtn = new javax.swing.JButton();
        itTableBtn = new javax.swing.JButton();
        workersTableBtn = new javax.swing.JButton();
        managementTableBtn = new javax.swing.JButton();
        accountingTableBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("First Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Last Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Gender :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Date of Birth :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Email :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Phone Number :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Hire Date :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Salary :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 51, 0));
        jLabel10.setText("\"Insert New Emplyee Information\"");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Department :");

        firstNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lastNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        maleRBtn.setBackground(new java.awt.Color(255, 204, 153));
        GenderGroup.add(maleRBtn);
        maleRBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        maleRBtn.setText("Male");
        maleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBtnActionPerformed(evt);
            }
        });

        femaleRBtn.setBackground(new java.awt.Color(255, 204, 153));
        GenderGroup.add(femaleRBtn);
        femaleRBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        femaleRBtn.setText("Female");

        dateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        phoneTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        addressTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        salaryTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        hireDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        emailTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        deptList.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        deptList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HR", "Accounting", "Quality Management", "IT", "Workers", "Management" }));
        deptList.setBorder(null);

        addEmployeeBtn.setBackground(new java.awt.Color(204, 51, 0));
        addEmployeeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addEmployeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeBtn.setText("Add Employee");
        addEmployeeBtn.setBorder(null);
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 3));

        hrTableBtn.setBackground(new java.awt.Color(153, 51, 0));
        hrTableBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hrTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrTableBtn.setText("Open HR Table");
        hrTableBtn.setBorder(null);
        hrTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrTableBtnActionPerformed(evt);
            }
        });

        qManagementTableBtn.setBackground(new java.awt.Color(153, 51, 0));
        qManagementTableBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qManagementTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        qManagementTableBtn.setText("Open Quality Management Table");
        qManagementTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qManagementTableBtnActionPerformed(evt);
            }
        });

        itTableBtn.setBackground(new java.awt.Color(153, 51, 0));
        itTableBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        itTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        itTableBtn.setText("Open IT Table");
        itTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itTableBtnActionPerformed(evt);
            }
        });

        workersTableBtn.setBackground(new java.awt.Color(153, 51, 0));
        workersTableBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        workersTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        workersTableBtn.setText("Open Workers Table");
        workersTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workersTableBtnActionPerformed(evt);
            }
        });

        managementTableBtn.setBackground(new java.awt.Color(153, 51, 0));
        managementTableBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        managementTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        managementTableBtn.setText("Open Management Table");
        managementTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementTableBtnActionPerformed(evt);
            }
        });

        accountingTableBtn.setBackground(new java.awt.Color(153, 51, 0));
        accountingTableBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accountingTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        accountingTableBtn.setText("Open Accounting Table");
        accountingTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountingTableBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qManagementTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workersTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managementTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountingTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(hrTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(qManagementTableBtn)
                .addGap(51, 51, 51)
                .addComponent(itTableBtn)
                .addGap(49, 49, 49)
                .addComponent(workersTableBtn)
                .addGap(46, 46, 46)
                .addComponent(managementTableBtn)
                .addGap(40, 40, 40)
                .addComponent(accountingTableBtn)
                .addGap(52, 52, 52))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("ID :");

        idTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deptList, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRBtn))
                                    .addComponent(dateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(lastNameTxt)
                                    .addComponent(firstNameTxt)
                                    .addComponent(idTxt)))))
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(75, 75, 75)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19))
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maleRBtn)
                                    .addComponent(femaleRBtn))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hireDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(deptList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(addEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRBtnActionPerformed

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
       
        maleRBtn.setActionCommand("Male");
        femaleRBtn.setActionCommand("Female");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String hireDateFormat = dateFormat.format(hireDate.getDate());
        String birthDateFormat = dateFormat.format(dateOfBirth.getDate());
        
        if(deptList.getSelectedItem().equals("HR")){
            try{
           String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
           String userNameDb = "sys as sysdba";
           String passDb = "1234";
           
           Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
           Statement statement = connection.createStatement();
           String Query = "insert into HR_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary,Department) Values ('"
                   +Integer.parseInt(idTxt.getText())+"' , '"+firstNameTxt.getText()+"' , '"+lastNameTxt.getText()+"' , '"+GenderGroup.getSelection().getActionCommand()+"' , '"+birthDateFormat
                   +"' , '"+emailTxt.getText()+"' , '"+Integer.parseInt(phoneTxt.getText())+"' , '"+addressTxt.getText()+"' , '"+hireDateFormat+"' , '"+Float.parseFloat(salaryTxt.getText())+"' , '"+deptList.getSelectedItem()+"')";
       statement.executeQuery(Query);
       JOptionPane.showMessageDialog(this, "Data Added To HR Table");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
        }else if(deptList.getSelectedItem().equals("Accounting")){
            try{
           String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
           String userNameDb = "sys as sysdba";
           String passDb = "1234";
           
           Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
           Statement statement = connection.createStatement();
           String Query = "insert into Accounting_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary,Department) Values ('"
                   +Integer.parseInt(idTxt.getText())+"' , '"+firstNameTxt.getText()+"' , '"+lastNameTxt.getText()+"' , '"+GenderGroup.getSelection().getActionCommand()+"' , '"+birthDateFormat
                   +"' , '"+emailTxt.getText()+"' , '"+Integer.parseInt(phoneTxt.getText())+"' , '"+addressTxt.getText()+"' , '"+hireDateFormat+"' , '"+Float.parseFloat(salaryTxt.getText())+"' , '"+deptList.getSelectedItem()+"')";
       statement.executeQuery(Query);
       JOptionPane.showMessageDialog(this, "Data Added To Accounting Table");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
        }else if(deptList.getSelectedItem().equals("IT")){
            try{
           String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
           String userNameDb = "sys as sysdba";
           String passDb = "1234";
           
           Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
           Statement statement = connection.createStatement();
           String Query = "insert into IT_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary,Department) Values ('"
                   +Integer.parseInt(idTxt.getText())+"' , '"+firstNameTxt.getText()+"' , '"+lastNameTxt.getText()+"' , '"+GenderGroup.getSelection().getActionCommand()+"' , '"+birthDateFormat
                   +"' , '"+emailTxt.getText()+"' , '"+Integer.parseInt(phoneTxt.getText())+"' , '"+addressTxt.getText()+"' , '"+hireDateFormat+"' , '"+Float.parseFloat(salaryTxt.getText())+"' , '"+deptList.getSelectedItem()+"')";
       statement.executeQuery(Query);
       JOptionPane.showMessageDialog(this, "Data Added To IT Table");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
        }else if(deptList.getSelectedItem().equals("Workers")){
            try{
           String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
           String userNameDb = "sys as sysdba";
           String passDb = "1234";
           
           Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
           Statement statement = connection.createStatement();
           String Query = "insert into Workers_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary,Department) Values ('"
                   +Integer.parseInt(idTxt.getText())+"' , '"+firstNameTxt.getText()+"' , '"+lastNameTxt.getText()+"' , '"+GenderGroup.getSelection().getActionCommand()+"' , '"+birthDateFormat
                   +"' , '"+emailTxt.getText()+"' , '"+Integer.parseInt(phoneTxt.getText())+"' , '"+addressTxt.getText()+"' , '"+hireDateFormat+"' , '"+Float.parseFloat(salaryTxt.getText())+"' , '"+deptList.getSelectedItem()+"')";
       statement.executeQuery(Query);
       JOptionPane.showMessageDialog(this, "Data Added To Workers Table");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
        }else if(deptList.getSelectedItem().equals("Quality Management")){
            try{
           String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
           String userNameDb = "sys as sysdba";
           String passDb = "1234";
           
           Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
           Statement statement = connection.createStatement();
           String Query = "insert into QualityManagement_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary,Department) Values ('"
                   +Integer.parseInt(idTxt.getText())+"' , '"+firstNameTxt.getText()+"' , '"+lastNameTxt.getText()+"' , '"+GenderGroup.getSelection().getActionCommand()+"' , '"+birthDateFormat
                   +"' , '"+emailTxt.getText()+"' , '"+Integer.parseInt(phoneTxt.getText())+"' , '"+addressTxt.getText()+"' , '"+hireDateFormat+"' , '"+Float.parseFloat(salaryTxt.getText())+"' , '"+deptList.getSelectedItem()+"')";
       statement.executeQuery(Query);
       JOptionPane.showMessageDialog(this, "Data Added To Quality Management Table");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
        }else if(deptList.getSelectedItem().equals("Management")){
            try{
           String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
           String userNameDb = "sys as sysdba";
           String passDb = "1234";
           
           Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
           Statement statement = connection.createStatement();
           String Query = "insert into Management_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary,Department) Values ('"
                   +Integer.parseInt(idTxt.getText())+"' , '"+firstNameTxt.getText()+"' , '"+lastNameTxt.getText()+"' , '"+GenderGroup.getSelection().getActionCommand()+"' , '"+birthDateFormat
                   +"' , '"+emailTxt.getText()+"' , '"+Integer.parseInt(phoneTxt.getText())+"' , '"+addressTxt.getText()+"' , '"+hireDateFormat+"' , '"+Float.parseFloat(salaryTxt.getText())+"' , '"+deptList.getSelectedItem()+"')";
       statement.executeQuery(Query);
       JOptionPane.showMessageDialog(this, "Data Added To Management Table");
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
        }
        
       
       
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void hrTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrTableBtnActionPerformed
            HrTable hrTable = new HrTable();
            hrTable.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_hrTableBtnActionPerformed

    private void accountingTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountingTableBtnActionPerformed
            AccountingTable accountingTable = new AccountingTable();
            accountingTable.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_accountingTableBtnActionPerformed

    private void qManagementTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qManagementTableBtnActionPerformed
            QualityManagementTable qualityManagementTable = new QualityManagementTable();
            qualityManagementTable.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_qManagementTableBtnActionPerformed

    private void itTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itTableBtnActionPerformed
            ITTable iTTable = new ITTable();
            iTTable.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_itTableBtnActionPerformed

    private void workersTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workersTableBtnActionPerformed
            WorkersTable workersTable = new WorkersTable();
            workersTable.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_workersTableBtnActionPerformed

    private void managementTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementTableBtnActionPerformed
            ManagementTable managementTable = new ManagementTable();
            managementTable.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_managementTableBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JButton accountingTableBtn;
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JTextField addressTxt;
    private de.wannawork.jcalendar.JCalendarComboBox dateOfBirth;
    private javax.swing.JComboBox deptList;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleRBtn;
    private javax.swing.JTextField firstNameTxt;
    private de.wannawork.jcalendar.JCalendarComboBox hireDate;
    private javax.swing.JButton hrTableBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton itTableBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JRadioButton maleRBtn;
    private javax.swing.JButton managementTableBtn;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton qManagementTableBtn;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton workersTableBtn;
    // End of variables declaration//GEN-END:variables
}
