/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iislamsoft
 */
public class QualityManagementTable extends javax.swing.JFrame {

    /**
     * Creates new form QualityManagementTable
     */
    public QualityManagementTable() {
        initComponents();
        refreshTable();
        maleRbtn.setActionCommand("Male");
        femaleRbtn.setActionCommand("Female");
    }
    public void refreshTable() {

        DefaultTableModel defaultTableModel = (DefaultTableModel) qualityTable.getModel();
        defaultTableModel.setRowCount(0);
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "select * from QualityManagement_Employee_Table";
            ResultSet rs = statement.executeQuery(Query);
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("ID"));
                String fn = String.valueOf(rs.getString("FirstName"));
                String ln = String.valueOf(rs.getString("LastName"));
                String gender = String.valueOf(rs.getString("Gender"));
                String birthDate = String.valueOf(rs.getString("DateOfBirth"));
                String email = String.valueOf(rs.getString("Email"));
                String phone = String.valueOf(rs.getInt("PhoneNumber"));
                String address = String.valueOf(rs.getString("Address"));
                String hireDate = String.valueOf(rs.getString("HireDate"));
                String sal = String.valueOf(rs.getInt("Salary"));

                String tableData[] = {id, fn, ln, gender, birthDate, email, phone, address, hireDate, sal};
                defaultTableModel = (DefaultTableModel) qualityTable.getModel();
                defaultTableModel.addRow(tableData);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qualityTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        birthDareCal = new de.wannawork.jcalendar.JCalendarComboBox();
        emailTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        hireDateCal = new de.wannawork.jcalendar.JCalendarComboBox();
        salTxt = new javax.swing.JTextField();
        addTxt = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteTxt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        maleRbtn = new javax.swing.JRadioButton();
        femaleRbtn = new javax.swing.JRadioButton();
        serchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setAutoscrolls(true);

        qualityTable.setBackground(new java.awt.Color(204, 51, 0));
        qualityTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        qualityTable.setForeground(new java.awt.Color(255, 255, 255));
        qualityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Gender", "Date of Birth", "Email", "Phone Number", "Address", "Hire Date", "Salary"
            }
        ));
        qualityTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qualityTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(qualityTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Last Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Date of Birth :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Email :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Phone Number :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Address :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Hire Date :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Salary :");

        firstNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lastNameTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        birthDareCal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        emailTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        phoneTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        addressTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        hireDateCal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        salTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        addTxt.setBackground(new java.awt.Color(0, 102, 102));
        addTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addTxt.setForeground(new java.awt.Color(255, 255, 255));
        addTxt.setText("Insert");
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(102, 102, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteTxt.setBackground(new java.awt.Color(204, 0, 0));
        deleteTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteTxt.setText("Delete");
        deleteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTxtActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back To Home Page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("ID :");

        idTxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Gender :");

        maleRbtn.setBackground(new java.awt.Color(255, 204, 153));
        genderGroup.add(maleRbtn);
        maleRbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        maleRbtn.setText("Male");

        femaleRbtn.setBackground(new java.awt.Color(255, 204, 153));
        genderGroup.add(femaleRbtn);
        femaleRbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        femaleRbtn.setText("Female");

        serchBtn.setBackground(new java.awt.Color(102, 0, 51));
        serchBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serchBtn.setForeground(new java.awt.Color(255, 255, 255));
        serchBtn.setText("Search");
        serchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthDareCal, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(addTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hireDateCal, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(serchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(maleRbtn)
                                .addGap(39, 39, 39)
                                .addComponent(femaleRbtn))
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(maleRbtn)
                    .addComponent(femaleRbtn))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(birthDareCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(serchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(deleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hireDateCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(salTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
         
        maleRbtn.setActionCommand("Male");
        femaleRbtn.setActionCommand("Female");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String hireDateFormat = dateFormat.format(hireDateCal.getDate());
        String birthDateFormat = dateFormat.format(birthDareCal.getDate());
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "update HR_Employee_Table set ID = '" + Integer.parseInt(idTxt.getText()) + "', FirstName = '" + firstNameTxt.getText()
                    + "' , LastName = '" + lastNameTxt.getText() + "', Gender = '" + genderGroup.getSelection().getActionCommand() + "', Email = '" + emailTxt.getText()
                    + "', PhoneNumber = '" + phoneTxt.getText() + "', Address = '" + addressTxt.getText() + "', Salary = '" + salTxt.getText() + "',HireDate = '" + hireDateFormat + "', DateOfBirth ='" + birthDateFormat + "' where ID = '" + Integer.parseInt(idTxt.getText()) + "'";

            statement.executeQuery(Query);
            JOptionPane.showMessageDialog(this, "Data Updated");

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

            refreshTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            HomePage homePage = new HomePage();
            homePage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void qualityTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qualityTableMouseClicked
       DefaultTableModel defaultTableModel = (DefaultTableModel) qualityTable.getModel();
        int rowIndex = qualityTable.getSelectedRow();

        idTxt.setText(defaultTableModel.getValueAt(rowIndex, 0).toString());
        firstNameTxt.setText(defaultTableModel.getValueAt(rowIndex, 1).toString());
        lastNameTxt.setText(defaultTableModel.getValueAt(rowIndex, 2).toString());
        if (defaultTableModel.getValueAt(rowIndex, 3).toString().equals("Female")) {
            femaleRbtn.setSelected(true);
        } else {
            maleRbtn.setSelected(true);
        }
        emailTxt.setText(defaultTableModel.getValueAt(rowIndex, 5).toString());
        phoneTxt.setText(defaultTableModel.getValueAt(rowIndex, 6).toString());
        addressTxt.setText(defaultTableModel.getValueAt(rowIndex, 7).toString());
        salTxt.setText(defaultTableModel.getValueAt(rowIndex, 9).toString());

        SimpleDateFormat parser = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formatter = new SimpleDateFormat("MMM DD, YY");
        Date birthDate, hireDate;
        try {
            birthDate = parser.parse(defaultTableModel.getValueAt(rowIndex, 4).toString());
            hireDate = parser.parse(defaultTableModel.getValueAt(rowIndex, 8).toString());

            birthDareCal.setDate(birthDate);
            hireDateCal.setDate(hireDate);
        } catch (ParseException ex) {
            Logger.getLogger(HrTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_qualityTableMouseClicked

    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
         maleRbtn.setActionCommand("Male");
        femaleRbtn.setActionCommand("Female");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String hireDateFormat = dateFormat.format(hireDateCal.getDate());
        String birthDateFormat = dateFormat.format(birthDareCal.getDate());

        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "insert into QualityManagement_Employee_Table (ID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Address,HireDate,Salary, Department) Values ('"
                    + Integer.parseInt(idTxt.getText()) + "' , '" + firstNameTxt.getText() + "' , '" + lastNameTxt.getText() + "' , '" + genderGroup.getSelection().getActionCommand() + "' , '" + birthDateFormat
                    + "' , '" + emailTxt.getText() + "' , '" + Integer.parseInt(phoneTxt.getText()) + "' , '" + addressTxt.getText() + "' , '" + hireDateFormat + "' , '" + Float.parseFloat(salTxt.getText()) + "' , '" + "HR')";
            statement.executeQuery(Query);
            JOptionPane.showMessageDialog(this, "Data Added");

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

            refreshTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_addTxtActionPerformed

    private void deleteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTxtActionPerformed
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "delete from QualityManagement_Employee_Table where ID = '" + Integer.parseInt(idTxt.getText()) + "'";
            statement.executeQuery(Query);
            JOptionPane.showMessageDialog(this, "Data Deleted");

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

            refreshTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_deleteTxtActionPerformed

    private void serchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchBtnActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) qualityTable.getModel();
        defaultTableModel.setRowCount(0);
        try {
            String urlDb = "jdbc:oracle:thin:@localhost:1521:ORCL2";
            String userNameDb = "sys as sysdba";
            String passDb = "1234";

            Connection connection = DriverManager.getConnection(urlDb, userNameDb, passDb);
            Statement statement = connection.createStatement();
            String Query = "select * from QualityManagement_Employee_Table where ID = '" + Integer.parseInt(idTxt.getText()) + "'";
            ResultSet rs = statement.executeQuery(Query);
            
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("ID"));
                String fn = String.valueOf(rs.getString("FirstName"));
                String ln = String.valueOf(rs.getString("LastName"));
                String genderType = String.valueOf(rs.getString("Gender"));
                String birthDate = String.valueOf(rs.getString("DateOfBirth"));
                String email = String.valueOf(rs.getString("Email"));
                String phone = String.valueOf(rs.getInt("PhoneNumber"));
                String address = String.valueOf(rs.getString("Address"));
                String hireDate = String.valueOf(rs.getString("HireDate"));
                String sal = String.valueOf(rs.getInt("Salary"));

                String tableData[] = {id, fn, ln, genderType, birthDate, email, phone, address, hireDate, sal};
                defaultTableModel = (DefaultTableModel) qualityTable.getModel();
                defaultTableModel.addRow(tableData);
                
                return;
            }

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Employee with entered data not exsit");
                refreshTable();
            }
            

            idTxt.setText("");
            firstNameTxt.setText("");
            lastNameTxt.setText("");
            femaleRbtn.setSelected(false);
            maleRbtn.setSelected(false);
            emailTxt.setText("");
            phoneTxt.setText("");
            addressTxt.setText("");
            salTxt.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_serchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QualityManagementTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QualityManagementTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QualityManagementTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QualityManagementTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QualityManagementTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTxt;
    private javax.swing.JTextField addressTxt;
    private de.wannawork.jcalendar.JCalendarComboBox birthDareCal;
    private javax.swing.JButton deleteTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleRbtn;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.ButtonGroup genderGroup;
    private de.wannawork.jcalendar.JCalendarComboBox hireDateCal;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JRadioButton maleRbtn;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTable qualityTable;
    private javax.swing.JTextField salTxt;
    private javax.swing.JButton serchBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
